/**
 * @param {string} natinality Person nationality
 * @param {string} dateOfBirth Person date of birth
 * @param {string} sex Person Sex
 * @param {string} dbIndex Which PK of this person in Database
 * @param {number} renewal How many times this person get new ID
 * @param {number} Random Number generated by the Sysytem
 */

export default (natinality, dateOfBirth, sex, dbIndex)=>{
    // format -> natinality, year of birth, sex, pk in db, renewal number, random number
    let ID = []
    const dateYear = new Date(dateOfBirth).getFullYear()

    // 1. Add nationality
    if(natinality==='rwandan'){
        ID.push(1)
    }else{
        ID.pus(2)
    }
    // 2. Add year of birth
    ID.push(dateYear)

    // 3. Add sex
    if(sex === 'male'){
        ID.push(8)
    }else{
        ID.push(7)
    }

    //4. Add person PK
    ID.push(dbIndex)

    // 5.Add renewal of identity
    ID.push(0)
    
    // 6. Generate two random number
    const randomNumber = Date.now()
    ID.push(randomNumber)
return ID
}